version: "2.1"
services:
    radarr:
        image: ghcr.io/linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=1001
            - PGID=1000
            - TZ=Europe/Amsterdam
        volumes:
            - /share/Container/radarr:/config
            - /share/Multimedia/Movies:/movies
            - /share/Downloads/completed/Movies:/downloads
        ports:
            - 7878:7878
        restart: unless-stopped

    nzbget:
        image: ghcr.io/linuxserver/nzbget
        container_name: nzbget
        environment:
            - PUID=1001
            - PGID=1000
            - TZ=Europe/Amsterdam
        volumes:
            - /share/Container/nzbget:/config
            - /share/Downloads:/downloads
        ports:
            - 6789:6789
        restart: unless-stopped

    sonarr:
        image: ghcr.io/linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1001
            - PGID=1000
            - TZ=Australia/Hobart
        volumes:
            - /share/Container/sonarr:/config
            - /share/Multimedia/TV:/tv
            - /share/Downloads/completed/TV:/downloads
        ports:
            - 8989:8989
        restart: unless-stopped

    plex:
        image: ghcr.io/linuxserver/plex
        container_name: plex
        network_mode: host
        environment:
            - PUID=1001
            - PGID=1000
            - VERSION=docker
        volumes:
            - /share/Container/plex:/config
            - /share/Multimedia/TV:/tv
            - /share/Multimedia/Movies:/movies
            - /share/Multimedia/Subtitles:/subtitles
            - /share/Backups/plex_db:/db_backups
        devices:
            - /dev/dri:/dev/dri
        restart: unless-stopped

    portainer:
        image: portainer/portainer
        container_name: portainer
        command: -H unix:///var/run/docker.sock
        environment:
            - TZ=Europe/Amsterdam
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /share/Container/portainer:/data
        ports:
            - 9000:9000
            - 8000:8000
        restart: unless-stopped

    bazarr:
        image: lscr.io/linuxserver/bazarr:latest
        container_name: bazarr
        environment:
            - PUID=1001
            - PGID=1000
            - TZ=Europe/Amsterdam
        volumes:
            - /share/Container/bazarr:/config
            - /share/Multimedia/Subtitles:/subtitles
        ports:
            - 6767:6767
        restart: unless-stopped

    overseerr:
        image: sctx/overseerr:latest
        container_name: overseerr
        environment:
            - PUID=1001
            - PGID=1000
            - TZ=Europe/Amsterdam
            - UMASK=002
        volumes:
            - /share/Container/overseerr:/app/config
        ports:
            - 5055:5055
        restart: unless-stopped

    prowlarr:
        image: lscr.io/linuxserver/prowlarr:develop
        container_name: prowlarr
        environment:
            - PUID=1001
            - PGID=1000
            - TZ=Europe/Amsterdam
            - UMASK=002
        volumes:
            - /share/Container/prowlarr:/config
        ports:
            - 9696:9696
        restart: unless-stopped

    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
            - PUID=1001
            - PGID=1000
            - TZ=Europe/Amsterdam
            - UMASK=002
            - WEBUI_PORT=8080
        volumes:
            - /share/Container/qbittorrent:/config
            - /share/Downloads:/downloads
        ports:
            - 8080:8080
            - 6881:6881
            - 6881:6881/udp
        restart: unless-stopped