version: "2.1"
services:
    radarr:
        image: ghcr.io/linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Amsterdam
        volumes:
            - /share/container/radarr:/config
            - /share/media/movies:/movies
            - /share/downloads/completed/movies:/downloads
        ports:
            - 7878:7878
        restart: unless-stopped

    nzbget:
        image: ghcr.io/linuxserver/nzbget
        container_name: nzbget
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Amsterdam
        volumes:
            - /share/container/nzbget:/config
            - /share/downloads:/downloads
        ports:
            - 6789:6789
        restart: unless-stopped

    sonarr:
        image: ghcr.io/linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Australia/Hobart
        volumes:
            - /share/container/sonarr:/config
            - /share/media/tv:/tv
            - /share/downloads/completed/tv:/downloads
        ports:
            - 8989:8989
        restart: unless-stopped

    plex:
        image: ghcr.io/linuxserver/plex
        container_name: plex
        network_mode: host
        environment:
            - PUID=1000
            - PGID=100
            - VERSION=docker
        volumes:
            - /share/container/plex:/config
            - /share/media/tv:/tv
            - /share/media/movies:/movies
            - /share/media/subtitles:/subtitles
            - /share/backup/plex_db:/db_backups
        devices:
            - /dev/dri:/dev/dri
        restart: unless-stopped

    portainer:
        image: portainer/portainer
        container_name: portainer
        command: -H unix:///var/run/docker.sock
        environment:
            - TZ=Europe/Amsterdam
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /share/container/portainer:/data
        ports:
            - 9000:9000
            - 8000:8000
        restart: unless-stopped

    bazarr:
        image: lscr.io/linuxserver/bazarr:latest
        container_name: bazarr
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Amsterdam
        volumes:
            - /share/container/bazarr:/config
            - /share/media/subtitles:/subtitles
        ports:
            - 6767:6767
        restart: unless-stopped

    overseerr:
        image: sctx/overseerr:latest
        container_name: overseerr
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Amsterdam
            - UMASK=002
        volumes:
            - /share/container/overseerr:/app/config
        ports:
            - 5055:5055
        restart: unless-stopped

    prowlarr:
        image: lscr.io/linuxserver/prowlarr:develop
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Amsterdam
            - UMASK=002
        volumes:
            - /share/container/prowlarr:/config
        ports:
            - 9696:9696
        restart: unless-stopped

    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Amsterdam
            - UMASK=002
            - WEBUI_PORT=8181
        volumes:
            - /share/container/qbittorrent:/config
            - /share/downloads:/downloads
        ports:
            - 8181:8181
            - 6881:6881
            - 6881:6881/udp
        restart: unless-stopped